### ISSUE TITLE
Issue with compiling 

### ISSUE THREAD

**Issue by mainey** [CJFreedom-Network/PegasusMod#2]
ant -f "C:\Users\Michael B\Documents\NetBeansProjects\PegasusMod-master" -Dnb.internal.action.name=build jar
C:\Users********\Documents\NetBeansProjects\PegasusMod-master\nbproject\build-impl.xml:226: Must set src.dir
BUILD FAILED (total time: 0 seconds)

something i missed? sry.

**Comment by Wild1145** [comment]
Try re-cloning the source from the Github page.

**Comment by mainey** [comment]
Fixed. Change project.properties file from IcarusMod, please try to reupload the correct project.properties again just to make sure. Thank you.
